[features]
seeds = false
skip-lint = false

[programs.localnet]
sollearning = "FpfRZaGL4sHYABnUxrr7U8956kH491RQTrHTwe9gGUAU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"